version: '3.7'
  mongoDb:
    image: mongo:latest
    container_name: 'mongo-dev-container'
    environment:
      MONGO_INITDB_DATABSE: my-db
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - 27001:27017
    volumes:
      - ./docker-entrypoint-initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  admin:
    image: dockette/adminer:full-php5
    restart: always
    ports: